In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [5]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [6]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
indep=dataset[['age', 'sex_male', 'bmi', 'children', 'smoker_yes']]
dep=dataset[['charges']]

In [8]:
indep

age  sex_male     bmi  children  smoker_yes
0      19         0  27.900         0           1
1      18         1  33.770         1           0
2      28         1  33.000         3           0
3      33         1  22.705         0           0
4      32         1  28.880         0           0
...   ...       ...     ...       ...         ...
1333   50         1  30.970         3           0
1334   18         0  31.920         0           0
1335   18         0  36.850         0           0
1336   21         0  25.800         0           0
1337   61         0  29.070         0           1

[1338 rows x 5 columns]

In [9]:
dep

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train

array([[-1.53963418, -0.98885138,  0.11036616, -0.90788827, -0.49929923],
       [ 0.74809711,  1.01127431,  0.26412451, -0.0755796 ,  2.00280702],
       [ 0.4621307 ,  1.01127431,  2.13997636,  1.58903774, -0.49929923],
       ...,
       [ 0.03318108,  1.01127431, -0.90443894, -0.90788827, -0.49929923],
       [-1.46814257,  1.01127431,  0.7869029 , -0.90788827, -0.49929923],
       [-0.46726014, -0.98885138, -1.96941782, -0.0755796 , -0.49929923]])

In [13]:
X_train.shape

(892, 5)

In [14]:
y_train

charges
482    1622.1885
338   41919.0970
356    8944.1151
869    4391.6520
182    4005.4225
...          ...
763    3070.8087
835    7160.3303
1216   5415.6612
559    1646.4297
684    4766.0220

[892 rows x 1 columns]

In [15]:
y_train.shape

(892, 1)

In [16]:
X_test

array([[ 0.89108031,  1.01127431, -0.07576237, -0.0755796 , -0.49929923],
       [ 0.5336223 , -0.98885138, -0.21009861, -0.0755796 , -0.49929923],
       [ 0.6051139 ,  1.01127431,  1.60182214,  0.75672907,  2.00280702],
       ...,
       [-1.46814257, -0.98885138,  0.65256665,  0.75672907,  2.00280702],
       [-0.82471815,  1.01127431,  0.37742013,  1.58903774, -0.49929923],
       [ 0.89108031, -0.98885138,  1.24817794,  0.75672907, -0.49929923]])

In [17]:
X_test.shape

(446, 5)

In [18]:
y_test

charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
261   17085.26760
1271   3021.80915
1313  36397.57600
2      4449.46200
405   11396.90020

[446 rows x 1 columns]

In [19]:
y_test.shape

(446, 1)

In [20]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression

# Define parameter grid as a dictionary
param_grid = {
    'copy_X': [True, False],
    'fit_intercept': [True, False],
    'n_jobs': [None, 1, -1],
    'positive': [True, False]
}

grid = GridSearchCV(LinearRegression(), param_grid, refit=True, verbose=3, n_jobs=-1)

# Fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


GridSearchCV(estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': [None, 1, -1], 'positive': [True, False]},
             verbose=3)

In [21]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)

# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': True}: 0.7864684814391834


In [22]:
import pickle

In [23]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
filename="mullinegrid_final.sav"
pickle.dump(regressor,open(filename,"wb"))

In [24]:
model=pickle.load(open(filename,"rb"))

In [25]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 33
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1


In [26]:
preinput=sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
preinput

C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.18217616, 65.01529649, -4.63995756, -0.90788827,  2.00280702]])

In [27]:
Future_Prediction=grid.predict(preinput)

#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[[17815.37262746]]
